using System.Security.Cryptography;
using System.Text;

namespace RainbowTableGenerator;

public static class Utils
{
    /// <summary>
    /// Simple tool for color console write
    /// </summary>
    public static void WriteColor(object message, ConsoleColor color = ConsoleColor.Gray)
    {
        Console.ForegroundColor = color;
        Console.WriteLine(message);
        Console.ResetColor();
    }

    /// <summary>
    /// Tool, that computes hash into SHA256 using ASCII encoding<br/>
    /// SHA256 generates 256-bit word with max 64 symbol length<br/>
    /// ASCII uses 7-bit to encode symbol<br/>
    /// Iterate throw generated bytes and build string with hexadecimal presentation for readability 
    /// </summary>
    public static string ComputeSHA256ASCIIHash(string input)
    {
        var bytes = SHA256.HashData(Encoding.ASCII.GetBytes(input));
        var builder = new StringBuilder();

        foreach (var b in bytes)
            builder.Append(b.ToString("x2"));

        return builder.ToString();
    }
}